<a href="https://colab.research.google.com/github/suinkangme/COMP432-GroupI/blob/main/Task2_RF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import sklearn
import sklearn.tree
import sklearn.ensemble
import sklearn.metrics
from google.colab import files
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

In [2]:
!gdown 1L5mB-u4-rZIt-CRVLEXPr6Li6W0d21ww
!gdown 1SAkn3JoiVPNxvOQZ97BznVSEcu1fmHDy

Downloading...
From: https://drive.google.com/uc?id=1L5mB-u4-rZIt-CRVLEXPr6Li6W0d21ww
To: /content/Dataset2_imagenet.csv
100% 32.0M/32.0M [00:00<00:00, 137MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SAkn3JoiVPNxvOQZ97BznVSEcu1fmHDy
To: /content/Dataset3_imagenet.csv
100% 31.9M/31.9M [00:00<00:00, 177MB/s]


In [3]:
data = pd.read_csv('Dataset2_imagenet.csv')
data2 = pd.read_csv('Dataset3_imagenet.csv')

In [4]:
test_size = 0.2
#random_state = 0

Without Gridsearch

In [5]:
X = data.values[:,:-1]
y = np.reshape(data.values[:,-1:], (6000,))
X_train, X_test, y_train, y_test = train_test_split(X, y.ravel(), test_size=test_size)

X2 = data2.values[:,:-1]
y2 = np.reshape(data2.values[:,-1:], (6000,))
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2.ravel(), test_size=test_size)

In [6]:
rf1 = sklearn.ensemble.RandomForestClassifier().fit(X_train, y_train)
rf2 = sklearn.ensemble.RandomForestClassifier().fit(X_train2, y_train2)

In [7]:
print('Dataset2_imagenet.csv') #this one
ya_pred = rf1.predict(X_train)
yb_pred = rf1.predict(X_test)
print("Training set:\n", confusion_matrix(y_train, ya_pred), "\n", classification_report(y_train, ya_pred))
print("Test set:\n", confusion_matrix(y_test, yb_pred),"\n", classification_report(y_test, yb_pred))
print("-----------------------------------------------------")

print('Dataset3_imagenet.csv')
ya_pred2 = rf2.predict(X_train2)
yb_pred2 = rf2.predict(X_test2)
print("Training set:\n", confusion_matrix(y_train2, ya_pred2), "\n", classification_report(y_train2, ya_pred2))
print("Test set:\n", confusion_matrix(y_test2, yb_pred2),"\n", classification_report(y_test2, yb_pred2))
print("-----------------------------------------------------")


Dataset2_imagenet.csv
Training set:
 [[1603    0    0]
 [   0 1624    0]
 [   0    0 1573]] 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1603
         1.0       1.00      1.00      1.00      1624
         2.0       1.00      1.00      1.00      1573

    accuracy                           1.00      4800
   macro avg       1.00      1.00      1.00      4800
weighted avg       1.00      1.00      1.00      4800

Test set:
 [[381  15   1]
 [ 18 358   0]
 [ 11   0 416]] 
               precision    recall  f1-score   support

         0.0       0.93      0.96      0.94       397
         1.0       0.96      0.95      0.96       376
         2.0       1.00      0.97      0.99       427

    accuracy                           0.96      1200
   macro avg       0.96      0.96      0.96      1200
weighted avg       0.96      0.96      0.96      1200

-----------------------------------------------------
Dataset3_imagenet.csv
Training 

With Gridsearch

In [8]:
rf3 = sklearn.ensemble.RandomForestClassifier()
param_grid1 = {'criterion': ['gini', 'entropy'],
               'max_depth': [3, 4, None],
               'min_samples_split': [2, 3, 4]}
grid1 = GridSearchCV(estimator=rf3, param_grid=param_grid1, scoring='accuracy')
grid1.fit(X_train, np.ravel(y_train))

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, None],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [11]:
rf4 = sklearn.ensemble.RandomForestClassifier()
param_grid2 = {'criterion': ['gini', 'entropy'],
               'max_depth': [3, 4, None],
               'min_samples_split': [2, 3, 4]}
grid2 = GridSearchCV(estimator=rf4, param_grid=param_grid2, scoring='accuracy')
grid2.fit(X_train2, np.ravel(y_train2))

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, None],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [12]:
print('Dataset2_imagenet.csv (with Gridsearch)')
ya_pred3 = grid1.predict(X_train)
yb_pred3 = grid1.predict(X_test)
print("Training set:\n", confusion_matrix(y_train, ya_pred3), "\n", classification_report(y_train, ya_pred3))
print("Test set:\n", confusion_matrix(y_test, yb_pred3),"\n", classification_report(y_test, yb_pred3))
print("-----------------------------------------------------")

print('Dataset3_imagenet.csv (with Gridsearch)')
ya_pred4 = grid2.predict(X_train2)
yb_pred4 = grid2.predict(X_test2)
print("Training set:\n", confusion_matrix(y_train2, ya_pred4), "\n", classification_report(y_train2, ya_pred4))
print("Test set:\n", confusion_matrix(y_test2, yb_pred4),"\n", classification_report(y_test2, yb_pred4))
print("-----------------------------------------------------")

Dataset2_imagenet.csv (with Gridsearch)
Training set:
 [[1603    0    0]
 [   0 1624    0]
 [   0    0 1573]] 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1603
         1.0       1.00      1.00      1.00      1624
         2.0       1.00      1.00      1.00      1573

    accuracy                           1.00      4800
   macro avg       1.00      1.00      1.00      4800
weighted avg       1.00      1.00      1.00      4800

Test set:
 [[380  16   1]
 [ 15 360   1]
 [ 14   1 412]] 
               precision    recall  f1-score   support

         0.0       0.93      0.96      0.94       397
         1.0       0.95      0.96      0.96       376
         2.0       1.00      0.96      0.98       427

    accuracy                           0.96      1200
   macro avg       0.96      0.96      0.96      1200
weighted avg       0.96      0.96      0.96      1200

-----------------------------------------------------
Dataset3_imag