<a href="https://colab.research.google.com/github/suinkangme/COMP432-GroupI/blob/main/Task2_RF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import sklearn
import sklearn.tree
import sklearn.ensemble
import sklearn.metrics
from google.colab import files
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

In [2]:
!gdown 1L5mB-u4-rZIt-CRVLEXPr6Li6W0d21ww

Downloading...
From: https://drive.google.com/uc?id=1L5mB-u4-rZIt-CRVLEXPr6Li6W0d21ww
To: /content/Dataset2_imagenet.csv
100% 32.0M/32.0M [00:00<00:00, 160MB/s] 


In [3]:
data = pd.read_csv('Dataset2_imagenet.csv')

In [4]:
test_size = 0.2
#random_state = 0

Without Gridsearch

In [5]:
X = data.values[:,:-1]
y = np.reshape(data.values[:,-1:], (6000,))
X_train, X_test, y_train, y_test = train_test_split(X, y.ravel(), test_size=test_size)


In [6]:
rf1 = sklearn.ensemble.RandomForestClassifier().fit(X_train, y_train)

In [9]:
print('Dataset2_imagenet.csv') #this one
ya_pred = rf1.predict(X_train)
yb_pred = rf1.predict(X_test)
print("Training set:\n", confusion_matrix(y_train, ya_pred), "\n", classification_report(y_train, ya_pred))
print("Test set:\n", confusion_matrix(y_test, yb_pred),"\n", classification_report(y_test, yb_pred))
print("-----------------------------------------------------")


Dataset2_imagenet.csv
Training set:
 [[1607    0    0]
 [   0 1612    0]
 [   0    0 1581]] 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1607
         1.0       1.00      1.00      1.00      1612
         2.0       1.00      1.00      1.00      1581

    accuracy                           1.00      4800
   macro avg       1.00      1.00      1.00      4800
weighted avg       1.00      1.00      1.00      4800

Test set:
 [[381  11   1]
 [ 20 367   1]
 [ 17   0 402]] 
               precision    recall  f1-score   support

         0.0       0.91      0.97      0.94       393
         1.0       0.97      0.95      0.96       388
         2.0       1.00      0.96      0.98       419

    accuracy                           0.96      1200
   macro avg       0.96      0.96      0.96      1200
weighted avg       0.96      0.96      0.96      1200

-----------------------------------------------------


With Gridsearch

In [10]:
rf2 = sklearn.ensemble.RandomForestClassifier()
param_grid1 = {'criterion': ['gini', 'entropy'],
               'max_depth': [3, 4, None],
               'min_samples_split': [2, 3, 4]}
grid1 = GridSearchCV(estimator=rf2, param_grid=param_grid1, scoring='accuracy')
grid1.fit(X_train, np.ravel(y_train))

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, None],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [11]:
print('Dataset2_imagenet.csv (with Gridsearch)')
ya_pred2 = grid1.predict(X_train)
yb_pred2 = grid1.predict(X_test)
print("Training set:\n", confusion_matrix(y_train, ya_pred2), "\n", classification_report(y_train, ya_pred2))
print("Test set:\n", confusion_matrix(y_test, yb_pred2),"\n", classification_report(y_test, yb_pred2))
print(grid1.best_params_)
print("-----------------------------------------------------")

Dataset2_imagenet.csv (with Gridsearch)
Training set:
 [[1607    0    0]
 [   0 1612    0]
 [   0    0 1581]] 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1607
         1.0       1.00      1.00      1.00      1612
         2.0       1.00      1.00      1.00      1581

    accuracy                           1.00      4800
   macro avg       1.00      1.00      1.00      4800
weighted avg       1.00      1.00      1.00      4800

Test set:
 [[382   9   2]
 [ 16 370   2]
 [ 16   0 403]] 
               precision    recall  f1-score   support

         0.0       0.92      0.97      0.95       393
         1.0       0.98      0.95      0.96       388
         2.0       0.99      0.96      0.98       419

    accuracy                           0.96      1200
   macro avg       0.96      0.96      0.96      1200
weighted avg       0.96      0.96      0.96      1200

{'criterion': 'gini', 'max_depth': None, 'min_samples_split': 3}
--